### ISSUE TITLE
How to Alphabetize

### ISSUE THREAD

**Issue by Joonpark13** [paralysedforce/cool-cs-things#1]
Should we alphabetize by author or title? Currently I've alphabetized it by title, but I could be convinced either way. Whichever we choose, we should make note of it in an CONTRIBUTING.md.

**Comment by paralysedforce** [comment]
Alphabetically by title should be fine, but as more entries are added, we should begin to categorize them into subsections. Right now, I don't think that we have nearly enough entries to create meaningful clusters, but we eventually should.
